version: "3.8"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: my-nginx-proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5000:80"
    restart: always
    networks:
      - my_network

networks:
  my_network:
    external: true